import { ThemePreset } from '../types/theme';

export const themePresets: ThemePreset[] = [
  {
    id: 'ocean',
    name: 'Ocean Blue',
    light: {
      name: 'Ocean Blue Light',
      id: 'ocean-light',
      colors: {
        primary: '#0EA5E9',
        secondary: '#0891B2',
        accent: '#06B6D4',
        background: '#F0FDFF',
        surface: '#FFFFFF',
        text: '#0F172A',
        textSecondary: '#334155',
        border: '#E0F2FE',
        error: '#EF4444',
        success: '#10B981',
        warning: '#F59E0B',
      },
    },
    dark: {
      name: 'Ocean Blue Dark',
      id: 'ocean-dark',
      colors: {
        primary: '#38BDF8',
        secondary: '#22D3EE',
        accent: '#67E8F9',
        background: '#0F172A',
        surface: '#1E293B',
        text: '#F1F5F9',
        textSecondary: '#CBD5E1',
        border: '#334155',
        error: '#F87171',
        success: '#34D399',
        warning: '#FBBF24',
      },
    },
  },
  {
    id: 'forest',
    name: 'Forest Green',
    light: {
      name: 'Forest Green Light',
      id: 'forest-light',
      colors: {
        primary: '#059669',
        secondary: '#047857',
        accent: '#10B981',
        background: '#F0FDF4',
        surface: '#FFFFFF',
        text: '#064E3B',
        textSecondary: '#065F46',
        border: '#DCFCE7',
        error: '#EF4444',
        success: '#10B981',
        warning: '#F59E0B',
      },
    },
    dark: {
      name: 'Forest Green Dark',
      id: 'forest-dark',
      colors: {
        primary: '#34D399',
        secondary: '#6EE7B7',
        accent: '#A7F3D0',
        background: '#064E3B',
        surface: '#065F46',
        text: '#F0FDF4',
        textSecondary: '#D1FAE5',
        border: '#14532D',
        error: '#F87171',
        success: '#34D399',
        warning: '#FBBF24',
      },
    },
  },

  {
    id: 'royal',
    name: 'Royal Purple',
    light: {
      name: 'Royal Purple Light',
      id: 'royal-light',
      colors: {
        primary: '#7C3AED',
        secondary: '#6D28D9',
        accent: '#8B5CF6',
        background: '#F5F3FF',
        surface: '#FFFFFF',
        text: '#4C1D95',
        textSecondary: '#5B21B6',
        border: '#EDE9FE',
        error: '#EF4444',
        success: '#10B981',
        warning: '#F59E0B',
      },
    },
    dark: {
      name: 'Royal Purple Dark',
      id: 'royal-dark',
      colors: {
        primary: '#A78BFA',
        secondary: '#C4B5FD',
        accent: '#DDD6FE',
        background: '#2E1065',
        surface: '#4C1D95',
        text: '#F5F3FF',
        textSecondary: '#E0E7FF',
        border: '#7C3AED',
        error: '#F87171',
        success: '#34D399',
        warning: '#FBBF24',
      },
    },
  },
  {
    id: 'monochrome',
    name: 'Monochrome',
    light: {
      name: 'Monochrome Light',
      id: 'monochrome-light',
      colors: {
        primary: '#525252',
        secondary: '#404040',
        accent: '#737373',
        background: '#FAFAFA',
        surface: '#F5F5F5',
        text: '#171717',
        textSecondary: '#525252',
        border: '#D4D4D4',
        error: '#DC2626',
        success: '#16A34A',
        warning: '#CA8A04',
      },
    },
    dark: {
      name: 'Monochrome Dark',
      id: 'monochrome-dark',
      colors: {
        primary: '#A3A3A3',
        secondary: '#737373',
        accent: '#525252',
        background: '#0A0A0A',
        surface: '#171717',
        text: '#FAFAFA',
        textSecondary: '#D4D4D4',
        border: '#404040',
        error: '#EF4444',
        success: '#22C55E',
        warning: '#EAB308',
      },
    },
  },
];